phase: "test"
batch_size: 1

img_info:
  img_size: 256
  n_components: 3


dataset:
  dataroot: datasets/test
  eye_box: rect

model:
  lambda_idt: 0.5
  lambda_A: 10.0
  lambda_B: 10.0
  lambda_his_lip: 1.0
  lambda_his_skin: 0.1
  lambda_his_eye: 1.0
  lambda_vgg: 0.005
  d_conv_dim: 64
  d_repeat_num: 3
  ngf: 64
  norm1: SN
  style_dim: 192
  n_downsampling: 2
  n_res: 3
  mlp_dim: 256
  input_nc: 3
  ispartial: False
  isinterpolation: False
  pretrained_path: ~
  vgg_root: vgg

fit:
  epochs: 100
  log_step: 10
  checkpoint_rate: 20
  beta1: 0.5
  beta2: 0.999
  g_lr: 0.0002
  d_lr: 0.0002
  g_step: 1

wandb:
  project: SCGAN
  entity: makeup_science
  name: default lambdas | dilate | g_step=1
  group: merged
  notes: ~
  local: False